server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092 # 카프카 주소
    producer:
      # 객체 -> JSON 문자열 변환 직렬화
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 10     # 10ms 정도 기다렸다 묶어 보내기 (Throughput 향상)
        batch.size: 16384

app:
  kafka:
    topic: taxi-event-data # 카프카 토픽 이름